@host = http://localhost:5500/api/v1


# ### Home page
# GET {{host}}

### Will differentiate different calls

### Get All players
GET {{host}}/players


### Get Specific player 
GET {{host}}/players/12



### Make sure there is space between "Content-Type...." to the JSON
POST {{host}}/players
Content-Type: application/json

{
    "id": 124,
    "email": "t@tt.com",
    "pass": "testTTT",
    "fName": "GioraTTT333T",
    "lName": "Glova",
    "buyInAmount": 24,
    "buyOutAmount": 122200,
    "role": "admin"
}
### CURRENT
### LOGIN # USER
POST {{host}}/players/login
Content-Type: application/json

{
    "email": "YonatanFriedman@google.com",
    "pass": "Yonatan_1"
}

### LOGIN # USER
POST {{host}}/players/login
Content-Type: application/json

{
    "email": "t@tt.com",
    "pass": "testTTT"
}


### LOGIN  ADMIN
POST {{host}}/players/login
Content-Type: application/json

{
    "email": "YonatanKatz@gmail.com",
    "pass": "Yonatan_1"
}


###

PUT {{host}}/players/24
Content-Type: application/json

{
    "id": 123,
    "fName": "GioraTTT333T",
    "lName": "Glova",
    "buyIn": 24,
    "buyOut": 100
}



### Delete [X]
DELETE {{host}}/players/123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsImVtYWlsIjoiWW9uYXRhbkthdHpAZ21haWwuY29tIiwiZk5hbWUiOiJZb25hdGFuIiwibE5hbWUiOiJLYXR6IiwiR2FtZVN0YXRzIjp7ImJ1eUluQW1vdW50Ijo1NDEsImJ1eU91dEFtb3VudCI6ODYwLCJnYWluT3JMb3NzIjozMTl9LCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDcwNDYyMzEsImV4cCI6MTc0NzA0OTgzMX0.-Bt8fkGDwTFSOJ75-Du2A92y_hDzI08gHPXlNL8K6_E


### Update NAME ONLY
PUT {{host}}/players/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjEsImVtYWlsIjoiWW9uYXRhbkthdHpAZ21haWwuY29tIiwiZk5hbWUiOiJZb25hdGFuIiwibE5hbWUiOiJLYXR6IiwiR2FtZVN0YXRzIjp7ImJ1eUluQW1vdW50Ijo1NDEsImJ1eU91dEFtb3VudCI6ODYwLCJnYWluT3JMb3NzIjozMTl9LCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDcwNDYyMzEsImV4cCI6MTc0NzA0OTgzMX0.-Bt8fkGDwTFSOJ75-Du2A92y_hDzI08gHPXlNL8K6_E
Content-Type: application/json

{
  "fName": "UpdatedName"
}

